routes/web.php
<?php
Route::Auth();
Route::get('/logout','Auth\LoginController@logout');
Route::get('/','UserController@index');
Route::get('/handle_youtube','youtubeController@index');
Route::post('/unprocessed','youtubeController@unProcessed');
Route::post('/file/setProcessed','youtubeController@setProcessed');
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group( ['middleware' => ['auth','authorize'],'roles' => ['Super'],'prefix' => "user", 'as' => "user."], function () {
    
    Route::get('/users', 'UserController@usersIndex')->name('usersindex');
    Route::get('{id}/users_1Edit', 'UserController@users_1Edit')->name('users_1Edit');
    Route::post('{id}/users_1Edit', 'UserController@users_1Update')->name('users_1Edit');
    Route::get('init', 'UserController@init')->name('init');
    Route::delete('{id}/delete', 'UserController@delete')->name('delete');
//--routes@@user

});
Route::group( ['middleware' => ['auth','can:super_user'],'prefix' => "event", 'as' => "event."], function () {
                    Route::get('/events', 'EventController@eventsIndex')->name('eventsindex');
    Route::get('{id}/events_1Edit', 'EventController@events_1Edit')->name('events_1Edit');
    Route::post('{id}/events_1Edit', 'EventController@events_1Update')->name('events_1Edit');
    Route::get('init', 'EventController@init')->name('init');
    Route::delete('{id}/delete', 'EventController@delete')->name('delete');
//--routes@@event

});
Route::group( ['middleware' => ['auth'],'prefix' => "event", 'as' => "event."], function () {
                    
    Route::get('{id}/event_details', 'EventController@event_details')->name('event_details');
    Route::get('{memory_id}/show_memory', 'EventController@show_memory')->name('show_memory');
    
//--routes@@event

});
Route::group(['middleware' => ['auth','can:super_user'],'prefix' => "task", 'as' => "task."], function () {
                    Route::get('/dishes', 'TaskController@dishesIndex')->name('dishesindex');
    Route::get('{id}/dishes_1Edit', 'TaskController@dishes_1Edit')->name('dishes_1Edit');
    Route::post('{id}/dishes_1Edit', 'TaskController@dishes_1Update')->name('dishes_1Edit');
    Route::get('init', 'TaskController@init')->name('init');
    Route::delete('{id}/delete', 'TaskController@delete')->name('delete');
//--routes@@task

});
Route::group(['middleware' => ['auth'],'prefix' => "task", 'as' => "task."], function () {
    Route::get('/pickup/{task_id}/{user_id}', 'TaskController@pickup')->name('pickup');
    Route::get('/comments/{task_id}', 'TaskController@comments')->name('comments');
//--routes@@task

});
Route::group( ['middleware' => ['auth','can:super_user'],'prefix' => "group", 'as' => "group."], function () {
                    Route::get('/groups', 'GroupController@groupsIndex')->name('groupsindex');
    Route::get('{id}/groups_1Edit', 'GroupController@groups_1Edit')->name('groups_1Edit');
    Route::post('{id}/groups_1Edit', 'GroupController@groups_1Update')->name('groups_1Edit');
    Route::get('init', 'GroupController@init')->name('init');
    Route::delete('{id}/delete', 'GroupController@delete')->name('delete');
//--routes@@group

});



Route::group( ['middleware' => ['auth'],'prefix' => "event_user", 'as' => "event_user."], function () {
                    Route::get('/invitations', 'EventUserController@invitationsIndex')->name('invitationsindex');
                    Route::get('/reply/{id}/{reply}', 'EventUserController@respondToEventInvitation')->name('reply');
                    Route::get('/reply_task/{id}/{reply}', 'EventUserController@respondToTaskInvitation')->name('reply_task');

//--routes@@event_user

});
Route::group( ['middleware' => ['auth'],'prefix' => "comment", 'as' => "comment."], function () {
                    Route::post('/do_comment', 'EventController@do_comment')->name('do_comment');
                    

//--routes@@event_user

});
Route::group( ['middleware' => ['auth'],'prefix' => "files", 'as' => "files."], function () {
                    Route::get('/add', 'memoryController@add')->name('add');
                    Route::post('/endpoint', 'fileController@handle')->name('endpoint');
                    Route::post('/save_file', 'fileController@saveFile')->name('save_file');
                    Route::delete('/endpoint/{file}', 'fileController@handle')->name('delete_endpoint');
                    Route::post('/get_file_info', 'fileController@getFileInfo')->name('get_file_info');
                    
    
//--routes@@files

});
//--routes--

resources/views/admin_includes/footer.blade.php
<div class="page-footer">
	<div class="page-footer-inner">
		 2017 &copy; Dish Party by. <a href="http://arabiclocalizer.com" title="Arabic Localizer Official Website" target="_blank">Arabic Localizer</a>
	</div>
	<div class="scroll-to-top">
		<i class="icon-arrow-up"></i>
	</div>
</div>

resources/views/admin_includes/header.blade.php
<div class="page-header navbar navbar-fixed-top">
	<!-- BEGIN HEADER INNER -->
	<div class="page-header-inner">
		<!-- BEGIN LOGO -->
		<div class="page-logo">
			
			<img src="http://arabiclocalizer.com/img/logo.png" alt="logo" height='28' style="margin-top:8px;"  class="logo-default"/>
			
			<div class="menu-toggler sidebar-toggler">
				<!-- DOC: Remove the above "hide" to enable the sidebar toggler button on header -->
			</div>
		</div>
		<!-- END LOGO -->
		<!-- BEGIN RESPONSIVE MENU TOGGLER -->
		<a href="javascript:;" class="menu-toggler responsive-toggler" data-toggle="collapse" data-target=".navbar-collapse">
		</a>
		<!-- END RESPONSIVE MENU TOGGLER -->
		<!-- BEGIN TOP NAVIGATION MENU -->
		<div class="page-top">
			<div class="top-menu">

				<ul class="nav navbar-nav pull-right">

					<!-- BEGIN NOTIFICATION DROPDOWN -->
					<!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->
					<li class="hide dropdown dropdown-extended dropdown-notification" id="header_notification_bar">
						<a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
							<i class="icon-bell"></i>
							<span class="badge badge-default">
					7 </span>
						</a>
						<ul class="dropdown-menu">
							<li class="external">
								<h3><span class="bold">12 pending</span> notifications</h3>
								<a href="extra_profile.html">view all</a>
							</li>
							<li>
								<ul class="dropdown-menu-list scroller" style="height: 250px;" data-handle-color="#637283">
									<li>
										<a href="javascript:;">
											<span class="time">just now</span>
											<span class="details">
									<span class="label label-sm label-icon label-success">
									<i class="fa fa-plus"></i>
									</span>
									New user registered. </span>
										</a>
									</li>
									<li>
										<a href="javascript:;">
											<span class="time">3 mins</span>
											<span class="details">
									<span class="label label-sm label-icon label-danger">
									<i class="fa fa-bolt"></i>
									</span>
									Server #12 overloaded. </span>
										</a>
									</li>
									<li>
										<a href="javascript:;">
											<span class="time">10 mins</span>
											<span class="details">
									<span class="label label-sm label-icon label-warning">
									<i class="fa fa-bell-o"></i>
									</span>
									Server #2 not responding. </span>
										</a>
									</li>
									<li>
										<a href="javascript:;">
											<span class="time">14 hrs</span>
											<span class="details">
									<span class="label label-sm label-icon label-info">
									<i class="fa fa-bullhorn"></i>
									</span>
									Application error. </span>
										</a>
									</li>
									<li>
										<a href="javascript:;">
											<span class="time">2 days</span>
											<span class="details">
									<span class="label label-sm label-icon label-danger">
									<i class="fa fa-bolt"></i>
									</span>
									Database overloaded 68%. </span>
										</a>
									</li>
									<li>
										<a href="javascript:;">
											<span class="time">3 days</span>
											<span class="details">
									<span class="label label-sm label-icon label-danger">
									<i class="fa fa-bolt"></i>
									</span>
									A user IP blocked. </span>
										</a>
									</li>
									<li>
										<a href="javascript:;">
											<span class="time">4 days</span>
											<span class="details">
									<span class="label label-sm label-icon label-warning">
									<i class="fa fa-bell-o"></i>
									</span>
									Storage Server #4 not responding dfdfdfd. </span>
										</a>
									</li>
									<li>
										<a href="javascript:;">
											<span class="time">5 days</span>
											<span class="details">
									<span class="label label-sm label-icon label-info">
									<i class="fa fa-bullhorn"></i>
									</span>
									System Error. </span>
										</a>
									</li>
									<li>
										<a href="javascript:;">
											<span class="time">9 days</span>
											<span class="details">
									<span class="label label-sm label-icon label-danger">
									<i class="fa fa-bolt"></i>
									</span>
									Storage server failed. </span>
										</a>
									</li>
								</ul>
							</li>
						</ul>
					</li>
					<!-- END NOTIFICATION DROPDOWN -->
					<!-- BEGIN INBOX DROPDOWN -->
					<!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->
					<li class="hide dropdown dropdown-extended dropdown-inbox" id="header_inbox_bar">
						<a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
							<i class="icon-envelope-open"></i>
							<span class="badge badge-default">
					4 </span>
						</a>
						<ul class="dropdown-menu">
							<li class="external">
								<h3>You have <span class="bold">7 New</span> Messages</h3>
								<a href="page_inbox.html">view all</a>
							</li>
							<li>
								<ul class="dropdown-menu-list scroller" style="height: 275px;" data-handle-color="#637283">
									<li>
										<a href="inbox.html?a=view">
									<span class="photo">
									<img src="/assets/admin/layout3/img/avatar2.jpg" class="img-circle" alt="">
									</span>
											<span class="subject">
									<span class="from">
									Lisa Wong </span>
									<span class="time">Just Now </span>
									</span>
											<span class="message">
									Vivamus sed auctor nibh congue nibh. auctor nibh auctor nibh... </span>
										</a>
									</li>
									<li>
										<a href="inbox.html?a=view">
									<span class="photo">
									<img src="/assets/admin/layout3/img/avatar3.jpg" class="img-circle" alt="">
									</span>
											<span class="subject">
									<span class="from">
									Richard Doe </span>
									<span class="time">16 mins </span>
									</span>
											<span class="message">
									Vivamus sed congue nibh auctor nibh congue nibh. auctor nibh auctor nibh... </span>
										</a>
									</li>
									<li>
										<a href="inbox.html?a=view">
									<span class="photo">
									<img src="/assets/admin/layout3/img/avatar1.jpg" class="img-circle" alt="">
									</span>
											<span class="subject">
									<span class="from">
									Bob Nilson </span>
									<span class="time">2 hrs </span>
									</span>
											<span class="message">
									Vivamus sed nibh auctor nibh congue nibh. auctor nibh auctor nibh... </span>
										</a>
									</li>
									<li>
										<a href="inbox.html?a=view">
									<span class="photo">
									<img src="/assets/admin/layout3/img/avatar2.jpg" class="img-circle" alt="">
									</span>
											<span class="subject">
									<span class="from">
									Lisa Wong </span>
									<span class="time">40 mins </span>
									</span>
											<span class="message">
									Vivamus sed auctor 40% nibh congue nibh... </span>
										</a>
									</li>
									<li>
										<a href="inbox.html?a=view">
									<span class="photo">
									<img src="/assets/admin/layout3/img/avatar3.jpg" class="img-circle" alt="">
									</span>
											<span class="subject">
									<span class="from">
									Richard Doe </span>
									<span class="time">46 mins </span>
									</span>
											<span class="message">
									Vivamus sed congue nibh auctor nibh congue nibh. auctor nibh auctor nibh... </span>
										</a>
									</li>
								</ul>
							</li>
						</ul>
					</li>
					<!-- END INBOX DROPDOWN -->
					<!-- BEGIN TODO DROPDOWN -->
					<!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->
					<li class="hide dropdown dropdown-extended dropdown-tasks" id="header_task_bar">
						<a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
							<i class="icon-calendar"></i>
							<span class="badge badge-default">
					3 </span>
						</a>
						<ul class="dropdown-menu extended tasks">
							<li class="external">
								<h3>You have <span class="bold">12 pending</span> tasks</h3>
								<a href="page_todo.html">view all</a>
							</li>
							<li>
								<ul class="dropdown-menu-list scroller" style="height: 275px;" data-handle-color="#637283">
									<li>
										<a href="javascript:;">
									<span class="task">
									<span class="desc">New release v1.2 </span>
									<span class="percent">30%</span>
									</span>
											<span class="progress">
									<span style="width: 40%;" class="progress-bar progress-bar-success" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100"><span class="sr-only">40% Complete</span></span>
									</span>
										</a>
									</li>
									<li>
										<a href="javascript:;">
									<span class="task">
									<span class="desc">Application deployment</span>
									<span class="percent">65%</span>
									</span>
											<span class="progress">
									<span style="width: 65%;" class="progress-bar progress-bar-danger" aria-valuenow="65" aria-valuemin="0" aria-valuemax="100"><span class="sr-only">65% Complete</span></span>
									</span>
										</a>
									</li>
									<li>
										<a href="javascript:;">
									<span class="task">
									<span class="desc">Mobile app release</span>
									<span class="percent">98%</span>
									</span>
											<span class="progress">
									<span style="width: 98%;" class="progress-bar progress-bar-success" aria-valuenow="98" aria-valuemin="0" aria-valuemax="100"><span class="sr-only">98% Complete</span></span>
									</span>
										</a>
									</li>
									<li>
										<a href="javascript:;">
									<span class="task">
									<span class="desc">Database migration</span>
									<span class="percent">10%</span>
									</span>
											<span class="progress">
									<span style="width: 10%;" class="progress-bar progress-bar-warning" aria-valuenow="10" aria-valuemin="0" aria-valuemax="100"><span class="sr-only">10% Complete</span></span>
									</span>
										</a>
									</li>
									<li>
										<a href="javascript:;">
									<span class="task">
									<span class="desc">Web server upgrade</span>
									<span class="percent">58%</span>
									</span>
											<span class="progress">
									<span style="width: 58%;" class="progress-bar progress-bar-info" aria-valuenow="58" aria-valuemin="0" aria-valuemax="100"><span class="sr-only">58% Complete</span></span>
									</span>
										</a>
									</li>
									<li>
										<a href="javascript:;">
									<span class="task">
									<span class="desc">Mobile development</span>
									<span class="percent">85%</span>
									</span>
											<span class="progress">
									<span style="width: 85%;" class="progress-bar progress-bar-success" aria-valuenow="85" aria-valuemin="0" aria-valuemax="100"><span class="sr-only">85% Complete</span></span>
									</span>
										</a>
									</li>
									<li>
										<a href="javascript:;">
									<span class="task">
									<span class="desc">New UI release</span>
									<span class="percent">38%</span>
									</span>
											<span class="progress progress-striped">
									<span style="width: 38%;" class="progress-bar progress-bar-important" aria-valuenow="18" aria-valuemin="0" aria-valuemax="100"><span class="sr-only">38% Complete</span></span>
									</span>
										</a>
									</li>
								</ul>
							</li>
						</ul>
					</li>
					<!-- END TODO DROPDOWN -->
					<!-- BEGIN USER LOGIN DROPDOWN -->
					<!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->
					<li class="dropdown dropdown-user">
						<a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
							{{--<img alt="" class=" img-circle" src="/images/user.png"/>--}}
							<span class="username username-hide-on-mobile">
					 {{Auth::user()->name}} </span>
							<i class="fa fa-angle-down"></i>
						</a>
						<ul class="dropdown-menu dropdown-menu-default">
							<li>
								<a href="/logout">
									<i class="icon-key"></i> Log Out </a>
							</li>
						</ul>
					</li>
					<!-- END USER LOGIN DROPDOWN -->
					<!-- BEGIN QUICK SIDEBAR TOGGLER -->
					<!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->
					<li class="hide dropdown dropdown-quick-sidebar-toggler">
						<a href="javascript:;" class="dropdown-toggle">
							<i class="icon-logout"></i>
						</a>
					</li>
					<!-- END QUICK SIDEBAR TOGGLER -->
				</ul>
			</div>

		</div>
		<!-- END TOP NAVIGATION MENU -->
	</div>
	<!-- END HEADER INNER -->
</div>

resources/views/admin_includes/hidden_attributes.blade.php
<div id="hiddenAttributes" data-default_page="@yield('default-page')" ></div>

resources/views/admin_includes/hints.blade.php
<!-- DOC: Apply "page-header-fixed-mobile" and "page-footer-fixed-mobile" class to body element to force fixed header or footer in mobile devices -->
<!-- DOC: Apply "page-sidebar-closed" class to the body and "page-sidebar-menu-closed" class to the sidebar menu element to hide the sidebar by default -->
<!-- DOC: Apply "page-sidebar-hide" class to the body to make the sidebar completely hidden on toggle -->
<!-- DOC: Apply "page-sidebar-closed-hide-logo" class to the body element to make the logo hidden on sidebar toggle -->
<!-- DOC: Apply "page-sidebar-hide" class to body element to completely hide the sidebar on sidebar toggle -->
<!-- DOC: Apply "page-sidebar-fixed" class to have fixed sidebar -->
<!-- DOC: Apply "page-footer-fixed" class to the body element to have fixed footer -->
<!-- DOC: Apply "page-sidebar-reversed" class to put the sidebar on the right side -->
<!-- DOC: Apply "page-full-width" class to the body element to have full width page without the sidebar menu -->

resources/views/admin_includes/meta.blade.php
<meta charset="utf-8"/>
<title>@yield('title')</title>
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<meta http-equiv="Content-type" content="text/html; charset=utf-8">
<meta content="" name="description"/>
<meta content="" name="author"/>
<meta name="csrf-token" content="{{ csrf_token() }}" />
<link rel="shortcut icon" href="{{asset('favicon.ico')}}">

resources/views/admin_includes/page_header.blade.php
			<h3 class="page-title">
				@yield('page_title') <small>@yield('page_title_small')</small>
				<div class="pull-right">
				<a href="javascript:;" class="btn blue"  id="back-btn" style="display:none;"  >
					<i class="fa fa-arrow-left"></i> Back </a>
			</div>
			</h3>
			

resources/views/admin_includes/sidebar.blade.php
<div class="page-sidebar-wrapper">
		<!-- DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing -->
		<!-- DOC: Change data-auto-speed="200" to adjust the sub menu slide up/down speed -->
		<div class="page-sidebar navbar-collapse collapse">
                    <!-- BEGIN SIDEBAR MENU -->
                    <!-- DOC: Apply "page-sidebar-menu-light" class right after "page-sidebar-menu" to enable light sidebar menu style(without borders) -->
                    <!-- DOC: Apply "page-sidebar-menu-hover-submenu" class right after "page-sidebar-menu" to enable hoverable(hover vs accordion) sub menu mode -->
                    <!-- DOC: Apply "page-sidebar-menu-closed" class right after "page-sidebar-menu" to collapse("page-sidebar-closed" class must be applied to the body element) the sidebar sub menu mode -->
                    <!-- DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing -->
                    <!-- DOC: Set data-keep-expand="true" to keep the submenues expanded -->
                    <!-- DOC: Set data-auto-speed="200" to adjust the sub menu slide up/down speed -->
            <div class="slimScrollDiv" style="position: relative; overflow: hidden;  ">

                <ul class="page-sidebar-menu  page-header-fixed " data-keep-expanded="false" data-auto-scroll="true" data-slide-speed="200" >
                    <!-- DOC: To remove the sidebar toggler from the sidebar you just need to completely remove the below "sidebar-toggler-wrapper" LI element -->
                    <li class="sidebar-toggler-wrapper">
                        <!-- BEGIN SIDEBAR TOGGLER BUTTON -->
                        <div class="sidebar-toggler">
                            <span></span>
                        </div>
                        <!-- END SIDEBAR TOGGLER BUTTON -->
                    </li>
                    <!-- DOC: To remove the search box from the sidebar you just need to completely remove the below "sidebar-search-wrapper" LI element -->
                    <li class="sidebar-search-wrapper">
                        <!-- BEGIN RESPONSIVE QUICK SEARCH FORM -->
                        <!-- DOC: Apply "sidebar-search-bordered" class the below search form to have bordered search box -->
                        <!-- DOC: Apply "sidebar-search-bordered sidebar-search-solid" class the below search form to have bordered & solid search box -->
                        <form class="sidebar-search hide" action="page_general_search_3.html" method="POST">
                            <a href="javascript:;" class="remove">
                                <i class="icon-close"></i>
                            </a>
                            <div class="input-group">
                                <input class="form-control" placeholder="Search..." type="text">
                                <span class="input-group-btn">
                                        <a href="javascript:;" class="btn submit">
                                            <i class="icon-magnifier"></i>
                                        </a>
                                    </span>
                            </div>
                        </form>
                        <!-- END RESPONSIVE QUICK SEARCH FORM -->
                    </li>
                    <h3></h3>
					@if(Auth::user()->user_type == "User")
                    <li class="nav-item start <?php if($i=='users'){?>active<?php ;}?>">
                        <a href="{{route('user.usersindex')}}" class="nav-link nav-toggle">
                            <i class="fa fa-user" aria-hidden="true"></i>
                            <span class="title">Users</span>
                        </a>

                    </li>
                     <li class="nav-item start <?php if($i=='groups'){?>active<?php ;}?>">
                        <a href="{{route('group.groupsindex')}}" class="nav-link nav-toggle">
                            <i class="fa fa-users" aria-hidden="true"></i>
                            <span class="title">Groups</span>
                        </a>

                    </li>
                    <li class="nav-item start <?php if($i=='events'){?>active<?php ;}?>">
                        <a href="{{route('event.eventsindex')}}" class="nav-link nav-toggle">
                            <i class="fa fa-folder" aria-hidden="true"></i>
                            <span class="title">Events</span>
                        </a>

                    </li>
                    <li class="nav-item start <?php if($i=='tasks'){?>active<?php ;}?>">
                        <a href="{{route('task.dishesindex')}}" class="nav-link nav-toggle">
                            <i class="fa fa-check" aria-hidden="true"></i>
                            <span class="title">Tasks</span>
                        </a>

                    </li>
                    @endif
                    
                    
                      <li class="nav-item start <?php if($i=='my_events'){?>active<?php ;}?>">
                        <a href="{{route('event_user.invitationsindex')}}" class="nav-link nav-toggle">
                            <i class="fa fa-clock-o" aria-hidden="true"></i>
                            <span class="title">My Events</span>
                        </a>

                    </li>
                    
                    
                   

                    <li class="hide nav-item start <?php if($i=='attendance_actions'){?>active<?php ;}?>">
                        <a href="#" class="nav-link nav-toggle">
                            <i class="fa fa-user"></i>
                            <span class="title">Attendance Actions</span>
                        </a>
                        <ul class="sub-menu">
                            <li class="nav-item <?php if($i=='attendance_actions' && $j =='Permissions'){?>active open<?php ;}?>">
                                <a href="/admin/requests/Permissions" class="nav-link ">
                                    <i class="fa fa-bolt"></i>
                                    <span class="title">Permissions</span>
                                </a>
                            </li>
                            <li class="nav-item <?php if($i=='attendance_actions' && $j =='Normal Leaves'){?>active open<?php ;}?>">
                                <a href="/admin/requests/Normal Leaves" class="nav-link ">
                                    <i class="fa fa-question-circle"></i>
                                    <span class="title">Normal Leaves</span>
                                </a>
                            </li>
                            <li class="nav-item <?php if($i=='attendance_actions' && $j =='Half Day'){?>active open<?php ;}?>">
                                <a href="/admin/requests/Half Day" class="nav-link ">
                                    <i class="fa fa-star-half-full"></i>
                                    <span class="title">Half Day</span>
                                </a>
                            </li>
                            <li class="nav-item <?php if($i=='attendance_actions' && $j =='Emergency Leaves'){?>active open<?php ;}?>">
                                <a href="/admin/requests/Emergency Leaves" class="nav-link ">
                                    <i class="fa fa-ambulance"></i>
                                    <span class="title">Emergency Leaves</span>
                                </a>
                            </li>
                            @if(Auth::user()->can_work_home == 1)
                                <li class="nav-item <?php if($i=='attendance_actions' && $j =='Home'){?>active open<?php ;}?>">
                                    <a href="/admin/requests/Home" class="nav-link ">
                                        <i class="fa fa-home"></i>
                                        <span class="title">Work From Home</span>
                                    </a>
                                </li>
                            @endif
                        </ul>


                    </li>



                </ul>
                <!-- END SIDEBAR MENU -->
                <!-- END SIDEBAR MENU -->
                <div class="slimScrollBar" style="background: rgb(187, 187, 187); width: 7px; position: absolute; top: 0px; opacity: 0.4; display: none; border-radius: 7px; z-index: 99; right: 1px; height: 1100px;"></div>
            </div>

        </div>
	</div>

resources/views/admin_includes/socket_connection.blade.php
@if(isset(Auth::user()->id))
<script type="text/javascript">
//var domain = window.location.hostname;
//conn = new Connection(<?php //echo Auth::user()->id;?>, "chatwindow", domain+":2000");
</script>
@endif