routes/web.php
<?php
Route::Auth();
Route::get('/logout','Auth\LoginController@logout');
Route::get('/','UserController@index');
Route::get('/handle_youtube','youtubeController@index');
Route::post('/unprocessed','youtubeController@unProcessed');
Route::post('/file/setProcessed','youtubeController@setProcessed');
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group( ['middleware' => ['auth','authorize'],'roles' => ['Super'],'prefix' => "user", 'as' => "user."], function () {
    
    Route::get('/users', 'UserController@usersIndex')->name('usersindex');
    Route::get('{id}/users_1Edit', 'UserController@users_1Edit')->name('users_1Edit');
    Route::post('{id}/users_1Edit', 'UserController@users_1Update')->name('users_1Edit');
    Route::get('init', 'UserController@init')->name('init');
    Route::delete('{id}/delete', 'UserController@delete')->name('delete');
//--routes@@user

});
Route::group( ['middleware' => ['auth','can:super_user'],'prefix' => "event", 'as' => "event."], function () {
                    Route::get('/events', 'EventController@eventsIndex')->name('eventsindex');
    Route::get('{id}/events_1Edit', 'EventController@events_1Edit')->name('events_1Edit');
    Route::post('{id}/events_1Edit', 'EventController@events_1Update')->name('events_1Edit');
    Route::get('init', 'EventController@init')->name('init');
    Route::delete('{id}/delete', 'EventController@delete')->name('delete');
//--routes@@event

});
Route::group( ['middleware' => ['auth'],'prefix' => "event", 'as' => "event."], function () {
                    
    Route::get('{id}/event_details', 'EventController@event_details')->name('event_details');
    Route::get('{memory_id}/show_memory', 'EventController@show_memory')->name('show_memory');
    
//--routes@@event

});
Route::group(['middleware' => ['auth','can:super_user'],'prefix' => "task", 'as' => "task."], function () {
                    Route::get('/dishes', 'TaskController@dishesIndex')->name('dishesindex');
    Route::get('{id}/dishes_1Edit', 'TaskController@dishes_1Edit')->name('dishes_1Edit');
    Route::post('{id}/dishes_1Edit', 'TaskController@dishes_1Update')->name('dishes_1Edit');
    Route::get('init', 'TaskController@init')->name('init');
    Route::delete('{id}/delete', 'TaskController@delete')->name('delete');
//--routes@@task

});
Route::group(['middleware' => ['auth'],'prefix' => "task", 'as' => "task."], function () {
    Route::get('/pickup/{task_id}/{user_id}', 'TaskController@pickup')->name('pickup');
    Route::get('/comments/{task_id}', 'TaskController@comments')->name('comments');
//--routes@@task

});
Route::group( ['middleware' => ['auth','can:super_user'],'prefix' => "group", 'as' => "group."], function () {
                    Route::get('/groups', 'GroupController@groupsIndex')->name('groupsindex');
    Route::get('{id}/groups_1Edit', 'GroupController@groups_1Edit')->name('groups_1Edit');
    Route::post('{id}/groups_1Edit', 'GroupController@groups_1Update')->name('groups_1Edit');
    Route::get('init', 'GroupController@init')->name('init');
    Route::delete('{id}/delete', 'GroupController@delete')->name('delete');
//--routes@@group

});



Route::group( ['middleware' => ['auth'],'prefix' => "event_user", 'as' => "event_user."], function () {
                    Route::get('/invitations', 'EventUserController@invitationsIndex')->name('invitationsindex');
                    Route::get('/reply/{id}/{reply}', 'EventUserController@respondToEventInvitation')->name('reply');
                    Route::get('/reply_task/{id}/{reply}', 'EventUserController@respondToTaskInvitation')->name('reply_task');

//--routes@@event_user

});
Route::group( ['middleware' => ['auth'],'prefix' => "comment", 'as' => "comment."], function () {
                    Route::post('/do_comment', 'EventController@do_comment')->name('do_comment');
                    

//--routes@@event_user

});
Route::group( ['middleware' => ['auth'],'prefix' => "files", 'as' => "files."], function () {
                    Route::get('/add', 'memoryController@add')->name('add');
                    Route::post('/endpoint', 'fileController@handle')->name('endpoint');
                    Route::post('/save_file', 'fileController@saveFile')->name('save_file');
                    Route::delete('/endpoint/{file}', 'fileController@handle')->name('delete_endpoint');
                    Route::post('/get_file_info', 'fileController@getFileInfo')->name('get_file_info');
                    
    
//--routes@@files

});
//--routes--

app/File.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class  File extends Model
{
    protected $table='files';
    protected $fillable=[ 'user_id', 'file', 'hash', 'file_type',];
    
 public function user(){
        return $this->belongsTo('App\User' ,  'user_id');
 }
}

app/Http/Controllers/fileController.php
<?php

namespace App\Http\Controllers;

use App\Http\Uploader\UploadHandler;

use Illuminate\Http\Request;
use App\File;
use App\Event;
use App\EventUser;
use App\User;
use App\Http\Helpers\Helpers;
use Auth;

class fileController extends Controller {

		public function __construct(){
			$this->dirPath = public_path('uploads');
		}
    	public function handle(Request $request){
		$data = $request->input();
    	$uploader = new UploadHandler();
    	

		// Specify the list of valid extensions, ex. array("jpeg", "xml", "bmp")
		$uploader->allowedExtensions = array(); // all files types allowed by default

		// Specify max file size in bytes.
		$uploader->sizeLimit = null;

		// Specify the input name set in the javascript.
		$uploader->inputName = "qqfile"; // matches Fine Uploader's default inputName value by default

		// If you want to use the chunking/resume feature, specify the folder to temporarily save parts.
		$uploader->chunksFolder = "chunks";

		//$method = $_SERVER["REQUEST_METHOD"];
		$method = $this->get_request_method();
    	// Determine whether we are dealing with a regular ol' XMLHttpRequest, or
		// an XDomainRequest
		$_HEADERS = $this->parseRequestHeaders();
		$iframeRequest = false;
		if (!isset($_HEADERS['X-Requested-With']) || $_HEADERS['X-Requested-With'] != "XMLHttpRequest") {
		    $iframeRequest = true;
		}

		/*
		 * handle the preflighted OPTIONS request. Needed for CORS operation.
		 */
		if ($method == "OPTIONS") {
		    $this->handlePreflight();
		}

		/*
		 * handle a DELETE request or a POST with a _method of DELETE.
		 */
		else if ($method == "DELETE") {
		    $this->handleCorsRequest();
		    $result = $uploader->handleDelete($this->dirPath);

		    // iframe uploads require the content-type to be 'text/html' and
		    // return some JSON along with self-executing javascript (iframe.ss.response)
		    // that will parse the JSON and pass it along to Fine Uploader via
		    // window.postMessage
		    if ($iframeRequest == true) {
		        header("Content-Type: text/html");
		        echo json_encode($result)."<script src='http://10.0.2.2/jquery.fineuploader-4.1.1/iframe.xss.response-4.1.1.js'></script>";
		    } else {
		        echo json_encode($result);
		    }
		}
		else if ($method == "POST") {
		    $this->handleCorsRequest();
		    header("Content-Type: text/plain");
		    
		    // Assumes you have a chunking.success.endpoint set to point here with a query parameter of "done".
		    // For example: /myserver/handlers/endpoint.php?done
		    if (isset($_GET["done"])) {
		        $result = $uploader->combineChunks($this->dirPath);
		    }
		    // Handles upload requests
		    else {
		        // Call handleUpload() with the name of the folder, relative to PHP's getcwd()
		        
        		
		        $result = $uploader->handleUpload($this->dirPath);

		        // To return a name used for uploaded file you can use the following line.
		        $result["uploadName"] = $uploader->getUploadName();
		        
		        


		        
		        // iframe uploads require the content-type to be 'text/html' and
		        // return some JSON along with self-executing javascript (iframe.ss.response)
		        // that will parse the JSON and pass it along to Fine Uploader via
		        // window.postMessage
		        if ($iframeRequest == true) {
		            header("Content-Type: text/html");
		            echo json_encode($result)."<script src='http://{{SERVER_URL}}/{{FINE_UPLOADER_FOLDER}}/iframe.xss.response.js'></script>";
		        } else {
		            echo json_encode($result);
		        }
		        
		    }
		}
		else {
		    header("HTTP/1.0 405 Method Not Allowed");
		}
	    }




		    public function get_request_method() {
		    global $HTTP_RAW_POST_DATA;

		    // This should only evaluate to true if the Content-Type is undefined
		    // or unrecognized, such as when XDomainRequest has been used to
		    // send the request.
		    if(isset($HTTP_RAW_POST_DATA)) {
		    	parse_str($HTTP_RAW_POST_DATA, $_POST);
		    }

		    if (isset($_POST["_method"]) && $_POST["_method"] != null) {
		        return $_POST["_method"];
		    }

		    return $_SERVER["REQUEST_METHOD"];
			}


			public function parseRequestHeaders() {
			    $headers = array();
			    foreach($_SERVER as $key => $value) {
			        if (substr($key, 0, 5) <> 'HTTP_') {
			            continue;
			        }
			        $header = str_replace(' ', '-', ucwords(str_replace('_', ' ', strtolower(substr($key, 5)))));
			        $headers[$header] = $value;
			    }
			    return $headers;
			}

			public function handleCorsRequest() {
			    header("Access-Control-Allow-Origin: *");
			}

			/*
			 * handle pre-flighted requests. Needed for CORS operation
			 */
			public function handlePreflight() {
			    handleCorsRequest();
			    header("Access-Control-Allow-Methods: POST, DELETE");
			    header("Access-Control-Allow-Credentials: true");
			    header("Access-Control-Allow-Headers: Content-Type, X-Requested-With, Cache-Control");
			}

			public function saveFile(Request $request){
				$data = $request->input();
				
				//Handle database 
		        $file = new File();
		        $file->file = $data['name'];
		        $file->user_id = Auth::user()->id;
		        $file->hash = $data["uuid"];
		        $finfo = finfo_open(FILEINFO_MIME_TYPE);
		        $mime = finfo_file($finfo, $this->dirPath."/".$data["uuid"]."/".$data['name']);

		        $file->file_type = $mime;
		        
		        $file->save();

		        // handle youtube videos
		        if (strpos($file->file_type, 'video') !== false) {
				    if($data['youtube_videos']){
				    	$file->processed = 2;
				    	$file->save();	
				    }
				}


		        // Handle file encryption
		        if($data['encrypt_files']){
		        	//encrypt files here

		        }

		        // should be deleted from here
		        $event = Event::where('admin_show',1)->first();
		        $participants = EventUser::get();
		        foreach($participants as $participant){
		        	$user = User::find($participant->user_id);
		        	$subject=Auth::user()->name." Has Added a New Memory in ".$event->name.".";
	                $msg="<p>".Auth::user()->name." has added a new memory in ".$event->name.".</p>
	 
	<p>To access the event, <a href='".route('event.event_details',['event_id' => $event->id])."'>Click Here</a> </p> 
	";
	                $title=" New Memory Added";
	                if($user){
	                    Helpers::sendEmail($subject,$msg,$user,$title);
	                }
		        }
		        
                
			}
			public function getFileInfo(Request $request){
				$data = $request->input();
				$file = File::find($data['id']);
				return response()->json([
					'processed'=>$file->processed,
					'href'=>'https://www.youtube.com/watch?v='.$file->youtube_id,
					'img' => 'https://img.youtube.com/vi/'.$file->youtube_id.'/0.jpg'

					]);

			}
		}

resources/views/File/base.blade.php
<?php
$i = 'files';
$j = '';
?>
<style>
.page-header.navbar.navbar-fixed-top,.page-footer .page-footer-inner,h3.page-title {
    display: none !important;
}
</style>
<style>
.comment_div{
	margin-left:10px;
	margin-bottom:30px;
}
.comment_div h5{
	color:#0088cc !important; 
	border-bottom:1px solid #d8d8d8; 
	padding-bottom:8px; 
	font-weight:bold;
}
.comment_div h5 span{
	color:#999; 
	font-weight:normal;
}
.comment_div p{
	margin:10px 0 !important;
}
</style>
@extends('admin.master')
@section('plugins_css')

    <link href="{{asset('assets/global/plugins/datetimepicker/bootstrap-datetimepicker.min.css')}}" rel="stylesheet" type="text/css" />
    <link href="{{asset('assets/global/plugins/bootstrap-toastr/toastr.min.css')}}" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" type="text/css" href="{{asset('assets/global/plugins/datatables/datatables.min.css')}}"/>
    <link rel="stylesheet" type="text/css" href="{{asset('assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css')}}"/>
    <link rel="stylesheet" type="text/css" href="{{asset('assets/global/plugins/sweetAlert/sweetalert.css')}}"/>
    <link rel="stylesheet" type="text/css" href="https://code.jquery.com/ui/1.12.0/themes/smoothness/jquery-ui.css"/>
    <link rel="stylesheet" href="{{asset('assets/j-folder/css/j-forms.css')}}">
    <link rel="stylesheet" href="{{asset('assets/global/plugins/dragula/dragula.css')}}"/>
@endsection
@section('plugins_js')

    {{--<script language="JavaScript" type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>--}}
    <script type="text/javascript" src="{{asset('assets/global/scripts/datatable.js')}}"></script>
    <script type="text/javascript" src="{{asset('assets/global/plugins/malsup.js')}}"></script>
    <script type="text/javascript" src="{{asset('assets/global/plugins/datatables/datatables.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js')}}"></script>
    <script type="text/javascript" src="{{asset('assets/global/plugins/datetimepicker/bootstrap-datetimepicker.js')}}"></script>
    <script type="text/javascript" src="{{asset('assets/global/plugins/bootstrap-toastr/toastr.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('assets/global/plugins/sweetAlert/sweetalert.min.js')}}"></script>
    <script  type="text/javascript" src="{{asset('assets/global/plugins/dragula/dragula.js')}}"></script>
@endsection

@section('page_js')

    <script type="text/javascript" src="{{asset('assets/admin/pages/scripts/task.js')}}"></script>
    <script type="text/javascript" src="{{asset('assets/admin/pages/scripts/comments.js')}}"></script>
    <script type="text/javascript" src="{{asset('assets/admin/pages/scripts/ajaxForms.js')}}"></script>

@endsection


@section('add_inits')

@stop


@section('page_title_small')

@stop

@section('content')
    
<?php 
// Uploader instantiation
$selector = "uploader";
$multiple = "true";
$allowed_extentions =array();
$maximum_file_size = 500000000000000000000;
$youtube_videos = "true";
$encrypt_files = "true";
 
?>
<div id="{{$selector}}"></div>
@include('vendor.fine-uploader.uploader')
@stop

resources/views/File/comments.blade.php
<style>
.page-header.navbar.navbar-fixed-top,.page-footer .page-footer-inner,h3.page-title {
    display: none !important;
}
</style>
<style>
.comment_div{
	margin-left:10px;
	margin-bottom:30px;
}
.comment_div h5{
	color:#0088cc !important; 
	border-bottom:1px solid #d8d8d8; 
	padding-bottom:8px; 
	font-weight:bold;
}
.comment_div h5 span{
	color:#999; 
	font-weight:normal;
}
.comment_div p{
	margin:10px 0 !important;
}
</style>
<h3> {{$task->name}} (<span id="comments_count">{{$comments_count}}</span>)</h3>
<form id="event_comments" class="ajax_form j-forms" method="post"
 action="{{route('comment.do_comment')}}">
 <div class="unit form-group ">
                    
                    <div class="input">
					<label class="icon-right">
                        <i class="fa fa-comment"></i>
                    </label>
                    <textarea  class="form-control comment"  name="comment"  data-name="Comment"  data-validation="" placeholder="Add a comment..." /></textarea>
                    </div>
</div>
<input name="event_id" value="{{$task->event_id}}" type="hidden" />
<input name="task_id" value="{{$task->id}}" type="hidden" />
<input type="reset" name="Reset" id="reset_button" value="Reset" style="display:none;" />
</form>
<div id="comment_container">

@foreach($comments as $comment)
<div class="comment_div" >
<h5 >{{$comment->user->name}} <span class="pull-right" ><?php echo date("l h:i a",strtotime($comment->created_at));?></span></h5>
<p>{{$comment->comment}}</p>
</div>
@endforeach
<div class="comment_div" style="display:none;">
<h5 >@@name@@ <span class="pull-right" >@@time@@</span></h5>
<p>@@comment@@</p>
</div>

</div>
<div class="comment_div clone_comment" style="display:none;">
<h5 >--name-- <span class="pull-right" >--time--</span></h5>
<p>--comment--</p>
</div>

resources/views/File/dishes.blade.php
<div class="portlet light">
    <div class="portlet-title">
        <div class="caption font-color">
            <i class="fa fa-globe font-color"></i> Dishes
        </div>

    </div>
    <div class="portlet-body">
        <div class="table-toolbar">
            <div class="row">
                <div class="col-md-6">
                    <div class="btn-group">
                        <a class="btn color pjax-link"  href="{{route('task.init')}}">
                            Add New <i class="fa fa-plus"></i>
                        </a>
                       
                    </div>
                </div>
{{--@reorder-button@--}}

            </div>
        </div>

    </div>
    <form id="search-form">
        {{csrf_field()}}
        
        <div class="form-group"></div>
    </form>

    <table class="table table-striped table-bordered table-hover table-dt" id="table-dt">

        <thead>
        <tr class="tr-head">
            <th valign="middle" class="no-sorting table-checkbox-col">
                <input type="checkbox" class="group-checkable">
            </th>
            <th valign="middle">
                        Name
                    </th>
            <th valign="middle">Category</th>
<th valign="middle">
                        Assigned By</th>
<th valign="middle">Assigned to</th>
<th valign="middle">Event name</th><th valign="middle">
                        Actions
                    </th>

        </tr>
        </thead>
        <tbody>
        @foreach($tasks as $index => $task)
        <tr class="odd gradeX" id="data-row-{{$task->id}}">
           <td valign="middle">
               <input type="hidden" value="{{$task->id}}" class="reorder-vals"/>
               <input type="checkbox" name="items[]" class="table-checkbox" value="{{$task->id}}"/>
           </td>
            <td valign="middle">
                        {{$task->name}}
                    </td>
            <td valign="middle">{{$task->category}}</td>
<td valign="middle">
                        <?php if(isset($task->assigned_by->name)){?>{{$task->assigned_by->name}}<?php ;}?>
                    </td>
<td valign="middle"><?php if(isset($task->user->name)){?>{{$task->user->name}}<?php ;}?></td><td valign="middle">{{$task->event->name}}</td><td valign="middle">
                        <a href="{{route('task.dishes_1Edit',['id'=>$task->id])}}" class="btn btn-edit  pjax-link" ><i class="fa fa-edit"></i> Edit</a>
                        <a href="{{route('task.delete',['id'=>$task->id ])}}" data-method="delete" class="btn btn-delete remove-stuff" ><i class="fa fa-remove"></i> Delete</a>
                    </td>
        </tr>
        @endforeach
        </tbody>
    </table>
</div>
<div class="portlet light">
    <div class="portlet-title">
        <div class="caption font-color">
            <i class="fa fa-globe font-color"></i> Dishes Pending Approval
        </div>

    </div>
    <div class="portlet-body">
        <div class="table-toolbar">
            <div class="row">
                <div class="col-md-6">
                    <div class="btn-group"></div>
                </div>
{{--@reorder-button@--}}

            </div>
        </div>

    </div>
    <form id="search-form">
        {{csrf_field()}}
        
        <div class="form-group"></div>
    </form>

    <table class="table table-striped table-bordered table-hover table-dt" id="table-dt">

        <thead>
        <tr class="tr-head">
            <th valign="middle">Dish</th>
            <th valign="middle">Event</th>
            <th valign="middle">Assigned to</th>
          <th valign="middle">
                        Assigned By
                    </th>
          <th valign="middle">
                        Actions
                    </th>
</tr>
        </thead>
        <tbody>
        @foreach($pending_tasks as $index => $task)
        <tr class="odd gradeX" id="data-row-{{$task->id}}">
           <td valign="middle">{{$task->name}}</td>
           <td valign="middle">
           <?php if(isset($task->event->name)){?>
           {{$task->event->name}}
           <?php ;}?>
           
           </td>
           <td valign="middle">
           <?php if(isset($task->user->name)){?>
           {{ $task->user->name }}
           <?php ;}?>
           </td>
          <td valign="middle">
          <?php if(isset($task->assigned_by->name)){?>
                        {{$task->assigned_by->name}}
                        <?php ;}?>
                    </td>
          <td valign="middle">
            @if($task->confirmed == "")
  <a href="{{route('event_user.reply_task',['id'=>$task->id , 'reply' => 1 ])}}" data-method="get" class="btn btn-success confirm_action" ><i class="fa fa-check"></i> Accept</a>
            <a href="{{route('event_user.reply_task',['id'=>$task->id , 'reply' => 0 ])}}" data-method="get" class="btn btn-delete confirm_action" ><i class="fa fa-remove"></i> Reject</a>
            @endif
          </td>
</tr>
        @endforeach
    </table>
</div>

resources/views/File/dishes_1.blade.php
<div class="portlet light bordered">
<div class="portlet-title">
        <div class="caption font-color">
            <i class="fa fa-gift font-color"></i>Task
        </div>
    </div>
    <div class="portlet-body form">
        <!-- BEGIN FORM-->
        <form id="main-form"  class="ajax_form j-forms" method="post" action="{{route('task.dishes_1Edit' , ['id'=>$task->id])}}">
            {{csrf_field()}}
            <div class="content">
                  <div class="unit form-group ">
                    <label class="label">Name</label>

                    <input value="{{$task->name}}" class="form-control" type="text" name="name" id="name" data-name="Name"  data-validation=",required" />
</div>
<div class="unit form-group ">
                    <label class="label">Description</label>
                    <div class="input">
					<label class="icon-right">
                        <i class="fa fa-edit"></i>
                    </label>
                    <textarea  class="form-control"  name="description" id="description" data-name="Description"  data-validation="" />
                    {{$task->description}}
                    </textarea>
                    </div>
</div>
<div class="unit form-group " >
                    <label class="label">Category</label>
                    <label class="input select">
                        <select name="category" id="category" class="form-control " data-name="Assigned to" data-validation=" ">
                            <option value="" @if(! $task->user_id) selected @endif >Select Category</option>
                            @foreach($categories as $category)
                                <option @if($task->category == $category->category) selected @endif value="{{$category->category}}">{{$category->category}}</option>
                            @endforeach
                            <option value="New Value" >New</option>
                        </select>
                        <input style="display:none;" value="" class="form-control new_type" type="text" name="new_type" id="new_type" data-name="new_type"  data-validation="" />
                        <span class="error_message error-view"></span>
                        <i></i>
                    </label>
                </div>
<div class="unit form-group " >
                    <label class="label">Assigned to</label>
                    <label class="input select">
                        <select name="user_id" id="user_id" class="form-control " data-name="Assigned to" data-validation=" ">
                            <option value="" @if(! $task->user_id) selected @endif >Task Pool</option>
                            @foreach($users as $user)
                                <option @if($task->user_id && ($task->user_id == $user->id)) selected @endif value="{{$user->id}}">{{$user->name}}</option>
                            @endforeach
                        </select>
                        <span class="error_message error-view"></span>
                        <i></i>
                    </label>
                </div>
<div class="unit form-group ">
                    <input value="{{Auth::user()->id}}" class="form-control" type="hidden" name="assigned_by_id" id="assigned_by_id" data-name="assigned_by_id"  data-validation="" />
</div>
<div class="unit form-group " >
          <label class="label">Event</label>
                    <label class="input select">
                        <select name="event_id" id="event_id" class="form-control " data-name="event_id" data-validation=",required ">
                            <option value="" @if(! $task->event_id) selected @endif disabled="">Select Event</option>
                            @foreach($events as $event)
                                <option @if($task->event_id && ($task->event_id == $event->id)) selected @endif value="{{$event->id}}">{{$event->name}}</option>
                            @endforeach
                        </select>
                        <span class="error_message error-view"></span>
                        <i></i>
                    </label>
                </div>

            </div>
            <div class="form-actions">
                <div class="btn-set pull-right">
                <!-- save as-->
                <input name="publish" type="submit" value="Save" class="btn btn-lg primary-btn"
                 id="publish"/>
                </div>
            </div>
        </form>
        <!-- END FORM-->
</div>
</div>

@include('vendor.lrgt.ajax_script', ['form' => '#main-form',
'request'=>'App/Http/Requests/dishes_1Request','on_start'=>false])