routes/web.php
<?php
Route::Auth();
Route::get('/logout','Auth\LoginController@logout');
Route::get('/','UserController@index');
Route::get('/handle_youtube','youtubeController@index');
Route::post('/unprocessed','youtubeController@unProcessed');
Route::post('/file/setProcessed','youtubeController@setProcessed');
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group( ['middleware' => ['auth','authorize'],'roles' => ['Super'],'prefix' => "user", 'as' => "user."], function () {
    
    Route::get('/users', 'UserController@usersIndex')->name('usersindex');
    Route::get('{id}/users_1Edit', 'UserController@users_1Edit')->name('users_1Edit');
    Route::post('{id}/users_1Edit', 'UserController@users_1Update')->name('users_1Edit');
    Route::get('init', 'UserController@init')->name('init');
    Route::delete('{id}/delete', 'UserController@delete')->name('delete');
//--routes@@user

});
Route::group( ['middleware' => ['auth','can:super_user'],'prefix' => "event", 'as' => "event."], function () {
                    Route::get('/events', 'EventController@eventsIndex')->name('eventsindex');
    Route::get('{id}/events_1Edit', 'EventController@events_1Edit')->name('events_1Edit');
    Route::post('{id}/events_1Edit', 'EventController@events_1Update')->name('events_1Edit');
    Route::get('init', 'EventController@init')->name('init');
    Route::delete('{id}/delete', 'EventController@delete')->name('delete');
//--routes@@event

});
Route::group( ['middleware' => ['auth'],'prefix' => "event", 'as' => "event."], function () {
                    
    Route::get('{id}/event_details', 'EventController@event_details')->name('event_details');
    Route::get('{memory_id}/show_memory', 'EventController@show_memory')->name('show_memory');
    
//--routes@@event

});
Route::group(['middleware' => ['auth','can:super_user'],'prefix' => "task", 'as' => "task."], function () {
                    Route::get('/dishes', 'TaskController@dishesIndex')->name('dishesindex');
    Route::get('{id}/dishes_1Edit', 'TaskController@dishes_1Edit')->name('dishes_1Edit');
    Route::post('{id}/dishes_1Edit', 'TaskController@dishes_1Update')->name('dishes_1Edit');
    Route::get('init', 'TaskController@init')->name('init');
    Route::delete('{id}/delete', 'TaskController@delete')->name('delete');
//--routes@@task

});
Route::group(['middleware' => ['auth'],'prefix' => "task", 'as' => "task."], function () {
    Route::get('/pickup/{task_id}/{user_id}', 'TaskController@pickup')->name('pickup');
    Route::get('/comments/{task_id}', 'TaskController@comments')->name('comments');
//--routes@@task

});
Route::group( ['middleware' => ['auth','can:super_user'],'prefix' => "group", 'as' => "group."], function () {
                    Route::get('/groups', 'GroupController@groupsIndex')->name('groupsindex');
    Route::get('{id}/groups_1Edit', 'GroupController@groups_1Edit')->name('groups_1Edit');
    Route::post('{id}/groups_1Edit', 'GroupController@groups_1Update')->name('groups_1Edit');
    Route::get('init', 'GroupController@init')->name('init');
    Route::delete('{id}/delete', 'GroupController@delete')->name('delete');
//--routes@@group

});



Route::group( ['middleware' => ['auth'],'prefix' => "event_user", 'as' => "event_user."], function () {
                    Route::get('/invitations', 'EventUserController@invitationsIndex')->name('invitationsindex');
                    Route::get('/reply/{id}/{reply}', 'EventUserController@respondToEventInvitation')->name('reply');
                    Route::get('/reply_task/{id}/{reply}', 'EventUserController@respondToTaskInvitation')->name('reply_task');

//--routes@@event_user

});
Route::group( ['middleware' => ['auth'],'prefix' => "comment", 'as' => "comment."], function () {
                    Route::post('/do_comment', 'EventController@do_comment')->name('do_comment');
                    

//--routes@@event_user

});
Route::group( ['middleware' => ['auth'],'prefix' => "files", 'as' => "files."], function () {
                    Route::get('/add', 'memoryController@add')->name('add');
                    Route::post('/endpoint', 'fileController@handle')->name('endpoint');
                    Route::post('/save_file', 'fileController@saveFile')->name('save_file');
                    Route::delete('/endpoint/{file}', 'fileController@handle')->name('delete_endpoint');
                    Route::post('/get_file_info', 'fileController@getFileInfo')->name('get_file_info');
                    
    
//--routes@@files

});
//--routes--

app/EventUser.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class  EventUser extends Model
{
    protected $table='event_users';
    protected $fillable=[ 'event_id', 'user_id', 'owner', 'participant', 'orgnizer', 'invited_by', 'status',];
    
 public function event(){
        return $this->hasOne('App\Event' , 'id','event_id');
 }
 public function user(){
        return $this->hasOne('App\User' , 'id','user_id');
 }
 public function getInviter(){
        return $this->hasOne('App\User' , 'id','invited_by');
 }
}

app/Http/Controllers/EventUserController.php
<?php

namespace App\Http\Controllers;

use App\Helpers\Helper;
use App\EventUser;
use Illuminate\Http\Request;
use Yajra\Datatables\Facades\Datatables;
use Illuminate\Support\Facades\Schema;
use Auth;
use App\Task;
use App\Http\Helpers\Helpers;
use App\User;
use App\Event;
//uses
class EventUserController extends Controller {


    public function invitationsIndex() {
        $data = [];
        //@@some-data@@
        $data['partialView'] = 'EventUser.invitations';
        $data['event_users'] = EventUser::orderBy('created_at', 'asc')->where('user_id',Auth::user()->id)->where('status','Pending')->get();
        $data['user_events'] = EventUser::orderBy('created_at', 'asc')->where('user_id',Auth::user()->id)->whereIn('status',array('Accepted','Rejected'))->get();
        $data['my_tasks'] = Task::orderBy('created_at', 'asc')
        ->where('user_id',Auth::user()->id)
        
        ->get();

        return view('EventUser.base', $data);
    }

    public function respondToEventInvitation($id,$reply){
    	$invitation = EventUser::find($id);
        $participant = User::find($invitation->user_id);
        $event = Event::find($invitation->event_id);
        $user = User::where('user_type','User')->first();
        if($reply == "Accepted" ){
            // Accepting event
            if($invitation->status =="Pending"){
                $subject = "
".$participant->name." Accepted Your Invitation to  ".$event->name."
";
                $msg = "
<p>Congratulations, ".$participant->name." has accepted your invitation to ".$event->name."</p>

<p>To access the event, <a href='".route('event.event_details',['event_id' => $event->id])."'>Click Here</a> </p>
            ";
                $title="Invitation Accepted";    
            }
            // Coming back to an event
            else{
                $subject = "
".$participant->name." Has Returned to ".$event->name."
";
                $msg = "
<p>Congratulations, ".$participant->name." has returned to  ".$event->name."</p>

<p>To access the event, <a href='".route('event.event_details',['event_id' => $event->id])."'>Click Here</a> </p>
            ";
                $title="Participant Returned to Event";    
            }

            }
            
            
            
           
            
        
        else{

            if($invitation->status =="Pending"){
                $subject = "
    ".$participant->name." Rejected Your Invitation to ".$event->name."
    ";
                $msg = "
    <p>Unfortunately, ".$participant->name." has declined your invitation to ".$event->name."</p>

    
                ";
                $title="Invitation Rejected";
            }
            else{
                $subject = "
    ".$participant->name." Has Left  ".$event->name."
    ";
                $msg = "
    <p>Unfortunately, ".$participant->name." has left  ".$event->name."</p>

    <p>Try to contact him to reconsider </p>
                ";
                $title="Participant Left Event";

            }
            
        }
    	$invitation->status = $reply;
    	$invitation->save();
        
        Helpers::sendEmail($subject,$msg,$user,$title);
        if($reply == "Accepted"){
            return response()->json(['page'=>route('event.event_details',['event_id' => $invitation->event_id ]) ]);
        }

    }

    public function respondToTaskInvitation($id,$reply){
    	$invitation = Task::find($id);
    	$invitation->confirmed = $reply;
        $event = Event::find($invitation->event_id);
        $task = $invitation;
        $participant = User::find($task->user_id);
    	if($reply ==0){
            $text = "Rejected";
            $text2 = "Unfortunately";
            $text3 = "Declined to Approve";
            $text4 ="Not Approved";
    		$invitation->user_id = Null;
            $invitation->confirmed = Null;    	
    	}else{
            $text = "Accepted";
            $text2 = "Congratulations";
            $text3 = "Approved";
            $text4 ="Approved";
        }
    	$invitation->save();
        // Organizer is reponding to a task 
        if(Auth::user()->user_type == "User"){
            $user=$participant;
            $subject = "
            ".Auth::user()->name." Has ".$text3." Assigning You ".$task->name." in ".$event->name."
     



    ";
                $msg = "".Auth::user()->name." has ".$text4." you to handle ".$task->name." in ".$event->name."
                ";
                $title="Request ".$text4;
                Helpers::sendEmail($subject,$msg,$user,$title);

        }
        // Participant is responding to am assigned task
        else{
            $user = User::where('user_type','User')->first();
            $subject = "
     

".$participant->name." Has ".$text." ".$task->name." in ".$event->name."

    ";
                $msg = "
    ".$text2.", ".$participant->name." has ".$text." the responsibility for ".$task->name." in ".$event->name."
                ";
                $title="Task ".$text;
                Helpers::sendEmail($subject,$msg,$user,$title);


        }
    }
//functions


}

resources/views/EventUser/base.blade.php
<?php
$i = 'my_events';
$j = '';
?>
@extends('admin.master')
@section('plugins_css')

    <link href="{{asset('assets/global/plugins/datetimepicker/bootstrap-datetimepicker.min.css')}}" rel="stylesheet" type="text/css" />
    <link href="{{asset('assets/global/plugins/bootstrap-toastr/toastr.min.css')}}" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" type="text/css" href="{{asset('assets/global/plugins/datatables/datatables.min.css')}}"/>
    <link rel="stylesheet" type="text/css" href="{{asset('assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css')}}"/>
    <link rel="stylesheet" type="text/css" href="{{asset('assets/global/plugins/sweetAlert/sweetalert.css')}}"/>
    <link rel="stylesheet" type="text/css" href="https://code.jquery.com/ui/1.12.0/themes/smoothness/jquery-ui.css"/>
    <link rel="stylesheet" href="{{asset('assets/j-folder/css/j-forms.css')}}">
    <link rel="stylesheet" href="{{asset('assets/global/plugins/dragula/dragula.css')}}"/>
@endsection
@section('plugins_js')

    {{--<script language="JavaScript" type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>--}}
    <script type="text/javascript" src="{{asset('assets/global/scripts/datatable.js')}}"></script>
    <script type="text/javascript" src="{{asset('assets/global/plugins/malsup.js')}}"></script>
    <script type="text/javascript" src="{{asset('assets/global/plugins/datatables/datatables.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js')}}"></script>
    <script type="text/javascript" src="{{asset('assets/global/plugins/datetimepicker/bootstrap-datetimepicker.js')}}"></script>
    <script type="text/javascript" src="{{asset('assets/global/plugins/bootstrap-toastr/toastr.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('assets/global/plugins/sweetAlert/sweetalert.min.js')}}"></script>
    <script  type="text/javascript" src="{{asset('assets/global/plugins/dragula/dragula.js')}}"></script>
@endsection

@section('page_js')

    <script type="text/javascript" src="{{asset('assets/admin/pages/scripts/EventUser.js')}}"></script>
    <script type="text/javascript" src="{{asset('assets/admin/pages/scripts/ajaxForms.js')}}"></script>

@endsection


@section('add_inits')

@stop


@section('page_title_small')

@stop

@section('content')
    @include($partialView)
@stop

resources/views/EventUser/invitations.blade.php
@if(count($event_users) != 0)
<div class="portlet light">
    <div class="portlet-title">
        <div class="caption font-color">
            <i class="fa fa-globe font-color"></i> Pending Invitations
      </div>

    </div>
    <div class="portlet-body">
        <div class="table-toolbar">
            <div class="row">

{{--@reorder-button@--}}

            </div>
        </div>

    </div>
    <form id="search-form">
        {{csrf_field()}}
        
        <div class="form-group"></div>
    </form>

    <table class="table table-striped table-bordered table-hover table-dt" id="table-dt">

        <thead>
        <tr class="tr-head">
            <th valign="middle">Event</th>
            <th valign="middle">Location</th>
            <th valign="middle">Timing</th>
          <th valign="middle">
                        Invited By
                    </th>
<th valign="middle">
                        Actions
                    </th>
</tr>
        </thead>
        <tbody>
        @foreach($event_users as $index => $event_user)
        <tr class="odd gradeX" id="data-row-{{$event_user->id}}">
           <td valign="middle"><a href="{{route('event.event_details',['event_id' => $event_user->event->id])}}" > {{$event_user->event->name}}</a></td>
           <td valign="middle">{{$event_user->event->location}}</td>
           <td valign="middle">
           {{ Carbon\Carbon::parse($event_user->event->start_time)->format('l d M Y h:i a') }} - {{ Carbon\Carbon::parse($event_user->event->end_time)->format('h:i a') }}
           </td>
          <td valign="middle">
                        {{$event_user->getInviter->name}}
                    </td>
<td valign="middle">
<a href="{{route('event_user.reply',['id'=>$event_user->id , 'reply' => 'Accepted' ])}}" data-method="get" class="btn btn-success confirm_action" ><i class="fa fa-check"></i> Accept</a>
                        <a href="{{route('event_user.reply',['id'=>$event_user->id , 'reply' => 'Rejected' ])}}" data-method="get" class="btn btn-delete confirm_action" ><i class="fa fa-remove"></i> Reject</a>
                    </td>
</tr>
        @endforeach
    </table>
</div>
@endif
@if(count($user_events) != 0)
<div class="portlet light">
    <div class="portlet-title">
        <div class="caption font-color">
            <i class="fa fa-globe font-color"></i> Your Events
      </div>

    </div>
    <div class="portlet-body">
        <div class="table-toolbar">
            <div class="row">

{{--@reorder-button@--}}

            </div>
        </div>

    </div>
  <form id="search-form">
        {{csrf_field()}}
        
        <div class="form-group"></div>
    </form>

    <table class="table table-striped table-bordered table-hover table-dt" id="table-dt">

        <thead>
        <tr class="tr-head">
            <th valign="middle">Event</th>
            <th valign="middle">Location</th>
            <th valign="middle">Timing</th>
          <th valign="middle">
                        Invited By
                    </th>
          <th valign="middle">Status</th>
<th valign="middle">
                        Actions
                    </th>
</tr>
        </thead>
        <tbody>
        @foreach($user_events as $index => $event_user)
        <tr class="odd gradeX" id="data-row-{{$event_user->id}}">
           <td valign="middle">
<a href="{{route('event.event_details',['event_id' => $event_user->event->id])}}" >
           {{$event_user->event->name}}
</a> 
           </td>
           <td valign="middle">{{$event_user->event->location}}</td>
           <td valign="middle">
           {{ Carbon\Carbon::parse($event_user->event->start_time)->format('l d M Y h:i a') }} - {{ Carbon\Carbon::parse($event_user->event->end_time)->format('h:i a') }}
           </td>
          <td valign="middle">
                      <?php if(isset($event_user->getInviter->name)){?>  {{$event_user->getInviter->name}}<?php ;}?>
                    </td>
          <td valign="middle">{{$event_user->status}}</td>
<td valign="middle">
@if($event_user->status == "Rejected")
<a href="{{route('event_user.reply',['id'=>$event_user->id , 'reply' => 'Accepted' ])}}" data-method="get" class="btn btn-success confirm_action" ><i class="fa fa-check"></i> Changed My Mind</a>
@endif
@if($event_user->status == "Accepted")
                        <a href="{{route('event_user.reply',['id'=>$event_user->id , 'reply' => 'Rejected' ])}}" data-method="get" class="btn btn-delete confirm_action" ><i class="fa fa-remove"></i> Leave Event</a>
                        @endif
                    </td>
</tr>
        @endforeach
    </table>
</div>
@endif

@if(count($my_tasks) != 0)
<div class="portlet light">
    <div class="portlet-title">
        <div class="caption font-color">
            <i class="fa fa-globe font-color"></i> Your Dishes
      </div>

    </div>
    <div class="portlet-body">
        <div class="table-toolbar">
            <div class="row">

{{--@reorder-button@--}}

            </div>
        </div>

    </div>
  <form id="search-form">
        {{csrf_field()}}
        
        <div class="form-group"></div>
    </form>

    <table class="table table-striped table-bordered table-hover table-dt" id="table-dt">

        <thead>
        <tr class="tr-head">
            <th valign="middle">Dish</th>
            <th valign="middle">Event</th>
            <th valign="middle">Timing</th>
          <th valign="middle">
                        Assigned By
                    </th>
          <th valign="middle">Approved By</th>
          <th valign="middle">
                        Actions
                    </th>
</tr>
        </thead>
        <tbody>
        @foreach($my_tasks as $index => $task)
        <tr class="odd gradeX" id="data-row-{{$task->id}}">
           <td valign="middle">{{$task->name}} <a href="{{route('task.comments',['task_id' => $task->id])}}" class="popup" ><i class="fa fa-edit font-color"></i> Comments {{$task->commentsCount->count()}}</a></td>
           <td valign="middle">{{$task->event->name}}</td>
           <td valign="middle">
           {{ Carbon\Carbon::parse($task->event->start_time)->format('l d M Y h:i a') }} - {{ Carbon\Carbon::parse($task->event->end_time)->format('h:i a') }}
           </td>
          <td valign="middle">
                        {{$task->assigned_by->name}}
                    </td>
          <td valign="middle">
          @if($task->assigned_by_id == $task->user_id)
          Organizer
          @else
          {{$task->user->name}}
          @endif
          </td>
          <td valign="middle">
            @if($task->confirmed == "" && $task->assigned_by_id != $task->user_id)
  <a href="{{route('event_user.reply_task',['id'=>$task->id , 'reply' => 1 ])}}" data-method="get" class="btn btn-success confirm_action" ><i class="fa fa-check"></i> Accept</a>
            <a href="{{route('event_user.reply_task',['id'=>$task->id , 'reply' => 0 ])}}" data-method="get" class="btn btn-delete confirm_action" ><i class="fa fa-remove"></i> Reject</a>
            @endif
          </td>
</tr>
        @endforeach
    </table>
</div>
@endif