routes/web.php
<?php
Route::Auth();
Route::get('/logout','Auth\LoginController@logout');
Route::get('/','UserController@index');
Route::get('/handle_youtube','youtubeController@index');
Route::post('/unprocessed','youtubeController@unProcessed');
Route::post('/file/setProcessed','youtubeController@setProcessed');
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group( ['middleware' => ['auth','authorize'],'roles' => ['Super'],'prefix' => "user", 'as' => "user."], function () {
    
    Route::get('/users', 'UserController@usersIndex')->name('usersindex');
    Route::get('{id}/users_1Edit', 'UserController@users_1Edit')->name('users_1Edit');
    Route::post('{id}/users_1Edit', 'UserController@users_1Update')->name('users_1Edit');
    Route::get('init', 'UserController@init')->name('init');
    Route::delete('{id}/delete', 'UserController@delete')->name('delete');
//--routes@@user

});
Route::group( ['middleware' => ['auth','can:super_user'],'prefix' => "event", 'as' => "event."], function () {
                    Route::get('/events', 'EventController@eventsIndex')->name('eventsindex');
    Route::get('{id}/events_1Edit', 'EventController@events_1Edit')->name('events_1Edit');
    Route::post('{id}/events_1Edit', 'EventController@events_1Update')->name('events_1Edit');
    Route::get('init', 'EventController@init')->name('init');
    Route::delete('{id}/delete', 'EventController@delete')->name('delete');
//--routes@@event

});
Route::group( ['middleware' => ['auth'],'prefix' => "event", 'as' => "event."], function () {
                    
    Route::get('{id}/event_details', 'EventController@event_details')->name('event_details');
    Route::get('{memory_id}/show_memory', 'EventController@show_memory')->name('show_memory');
    
//--routes@@event

});
Route::group(['middleware' => ['auth','can:super_user'],'prefix' => "task", 'as' => "task."], function () {
                    Route::get('/dishes', 'TaskController@dishesIndex')->name('dishesindex');
    Route::get('{id}/dishes_1Edit', 'TaskController@dishes_1Edit')->name('dishes_1Edit');
    Route::post('{id}/dishes_1Edit', 'TaskController@dishes_1Update')->name('dishes_1Edit');
    Route::get('init', 'TaskController@init')->name('init');
    Route::delete('{id}/delete', 'TaskController@delete')->name('delete');
//--routes@@task

});
Route::group(['middleware' => ['auth'],'prefix' => "task", 'as' => "task."], function () {
    Route::get('/pickup/{task_id}/{user_id}', 'TaskController@pickup')->name('pickup');
    Route::get('/comments/{task_id}', 'TaskController@comments')->name('comments');
//--routes@@task

});
Route::group( ['middleware' => ['auth','can:super_user'],'prefix' => "group", 'as' => "group."], function () {
                    Route::get('/groups', 'GroupController@groupsIndex')->name('groupsindex');
    Route::get('{id}/groups_1Edit', 'GroupController@groups_1Edit')->name('groups_1Edit');
    Route::post('{id}/groups_1Edit', 'GroupController@groups_1Update')->name('groups_1Edit');
    Route::get('init', 'GroupController@init')->name('init');
    Route::delete('{id}/delete', 'GroupController@delete')->name('delete');
//--routes@@group

});



Route::group( ['middleware' => ['auth'],'prefix' => "event_user", 'as' => "event_user."], function () {
                    Route::get('/invitations', 'EventUserController@invitationsIndex')->name('invitationsindex');
                    Route::get('/reply/{id}/{reply}', 'EventUserController@respondToEventInvitation')->name('reply');
                    Route::get('/reply_task/{id}/{reply}', 'EventUserController@respondToTaskInvitation')->name('reply_task');

//--routes@@event_user

});
Route::group( ['middleware' => ['auth'],'prefix' => "comment", 'as' => "comment."], function () {
                    Route::post('/do_comment', 'EventController@do_comment')->name('do_comment');
                    

//--routes@@event_user

});
Route::group( ['middleware' => ['auth'],'prefix' => "files", 'as' => "files."], function () {
                    Route::get('/add', 'memoryController@add')->name('add');
                    Route::post('/endpoint', 'fileController@handle')->name('endpoint');
                    Route::post('/save_file', 'fileController@saveFile')->name('save_file');
                    Route::delete('/endpoint/{file}', 'fileController@handle')->name('delete_endpoint');
                    Route::post('/get_file_info', 'fileController@getFileInfo')->name('get_file_info');
                    
    
//--routes@@files

});
//--routes--

app/Event.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class  Event extends Model
{
    protected $table='events';
    protected $fillable=[ 'name', 'location', 'latitude', 'longitude', 'cost', 'reminders', 'event_image', 'description', 'end_time', 'start_time',];
    
 public function Detail(){
        return $this->belongsToMany('App\Detail' );
    }
    public function PoolDishes(){
        return $this->hasMany('App\Task' )->whereNull('tasks.user_id')->orderBy('category');
    }
    public function AssignedDishes(){
        return $this->hasMany('App\Task' )->whereNotNull('tasks.user_id');
    }
 public function AcceptedUsers(){
        return $this->belongsToMany('App\User','event_users' )->where('event_users.status','Accepted');
    }
    public function PendingUsers(){
        return $this->belongsToMany('App\User','event_users' )->where('event_users.status','Pending');
    }
}

app/Http/Controllers/EventController.php
<?php

namespace App\Http\Controllers;

use App\Helpers\Helper;
use App\Event;
use Illuminate\Http\Request;
use Yajra\Datatables\Facades\Datatables;
use Illuminate\Support\Facades\Schema;
use App\User;
use App\EventUser;
use App\Group;
use App\GroupUser;
use Auth;
use Mail;
use App\File;
use App\Comment;
use App\Http\Helpers\Helpers;
use App\Task;
//uses
class EventController extends Controller {


    public function eventsIndex() {
        $data = [];
        //@@some-data@@
        $data['partialView'] = 'Event.events';
        $data['events'] = Event::orderBy('created_at', 'asc')->where('admin_show',1)->get();
        return view('Event.base', $data);
    }
    public function events_1Edit($id) {
        $event = Event::findOrFail($id);
        $users = User::where('admin_show',1)->where('user_type','user')->get();
        $groups = Group::where('admin_show',1)->get();
        $data = [];
    $data['partialView'] = 'Event.events_1';
        $data['event'] = $event;
        $data['users'] = $users;
        $data['groups'] = $groups;
        return view('Event.base', $data);
    }
    public function events_1Update(Request $request, $id) {
        $data = $request->input();
        $event = Event::findOrFail($id);
        
$event->admin_show=1;
$event->update($request->all());//if you use array inputs, you should use $request->except([array inputs])
// invite users
if(isset($data['users'])){
    foreach($data['users'] as $user){
        $check_already_invited = EventUser::where('event_id',$id)->where('user_id',$user)->count();
        if($check_already_invited == 0){
            $new_invitation = new EventUser();
            $new_invitation->user_id = $user;
            $new_invitation->event_id = $id;
            $new_invitation->status = "Pending";
            $new_invitation->participant = 1;
            $new_invitation->owner = 0;
            $new_invitation->orgnizer = 0;
            $new_invitation->invited_by = Auth::user()->id;
            $new_invitation->save();
            $event = Event::find($id);
            $user= User::find($user);
                $subject = Auth::user()->name." Invites you to ".$event->name;
                $msg = "<p>Dear ".$user->name.",</p>

".Auth::user()->name." <p>has invited to attend ".$event->name." hosted at ".$event->location." at ".$event->start_time." and would very much like for you to accept.</p>

<p>To accept please <a href='http://events.arabiclocalizer.info'>click here</a> and login with the following credentials:</p>
<p>Username: ".$user->email."</p>
<p>Password: 123456 </p>

<p>Please feel free to pick up a task from the list of tasks available in the event and wait for the event organizer’s approval. </p>

<p>Many Thanks,</p>
".Auth::user()->name."";
$title = "New Event Invitation";
                Helpers::sendEmail($subject,$msg,$user,$title);
        }

    }
}
// invite groups
if(isset($data['groups'])){
    foreach($data['groups'] as $group_id){
        $group = Group::find($group_id);
        //dd($group);
        $user_emails = explode(",", $group->users);
        foreach($user_emails as $email){
            $user = User::where('email',$email)->first();
            
            $check_already_invited = EventUser::where('event_id',$id)->where('user_id',$user->id)->count();
            if($check_already_invited == 0){
                $new_invitation = new EventUser();
                $new_invitation->user_id = $user->id;
                $new_invitation->event_id = $id;
                $new_invitation->status = "Pending";
                $new_invitation->participant = 1;
                $new_invitation->owner = 0;
                $new_invitation->orgnizer = 0;
                $new_invitation->invited_by = Auth::user()->id;
                $new_invitation->save();

                $event = Event::find($id);
                $subject = Auth::user()->name." Invites you to ".$event->name;
                $msg = "<p>Dear ".$user->name.",</p>

".Auth::user()->name." <p>has invited to attend ".$event->name." hosted at ".$event->location." at ".$event->start_time." and would very much like for you to accept.</p>

<p>To accept please <a href='http://events.arabiclocalizer.info'>click here</a> and login with the following credentials:</p>
<p>Username: ".$user->email."</p>
<p>Password: 123456 </p>

<p>Please feel free to pick up a task from the list of tasks available in the event and wait for the event organizer’s approval. </p>

<p>Many Thanks,</p>
".Auth::user()->name."";
$title = "New Event Invitation";
                Helpers::sendEmail($subject,$msg,$user,$title);
            }

        }
        

    }
}
// make the admin a participant
$check_already_invited = EventUser::where('event_id',$id)->where('user_id',Auth::user()->id)->count();
            if($check_already_invited == 0){
                $new_invitation = new EventUser();
                $new_invitation->user_id = Auth::user()->id;
                $new_invitation->event_id = $id;
                $new_invitation->status = "Accepted";
                $new_invitation->participant = 1;
                $new_invitation->owner = 1;
                $new_invitation->orgnizer = 1;
                $new_invitation->save();
            }
return response()->json(['status'=>'success','msg'=>'Event successfully saved','url' => route('event.eventsindex')]);
    }
    public function init() {
        $event = new Event();
        $event->save();
        return redirect(route('event.events_1Edit', ['id' => $event->id]));
    }

    public function event_details($id) {
        $event = Event::findOrFail($id);
        $users = User::where('admin_show',1)->where('user_type','user')->get();
        $groups = Group::where('admin_show',1)->get();
        $files = File::get();
        $comments = Comment::where('event_id',$event->id)->where('task_id',0)->orderBy('created_at','DESC')->get();
        $comments_count = Comment::where('event_id',$event->id)->where('task_id',0)->count();
        $data = [];
    $data['partialView'] = 'Event.event_details';
        $data['event'] = $event;
        $data['users'] = $users;
        $data['files'] = $files;
        $data['comments'] = $comments;
        $data['comments_count'] = $comments_count;
        $data['groups'] = $groups;
        return view('Event.base', $data);
    }
public function delete($id) {        Event::destroy($id) or abort(404);    
}

public function do_comment(Request $request){
    $data = $request->input();
    $comment = new Comment();
    $comment->comment = $data['comment'];
    $comment->event_id = $data['event_id'];
    $comment->task_id = $data['task_id'];
    if(isset($data['memory_id'])){
        $comment->memory_id = $data['memory_id'];    
    }
    $comment->user_id = Auth::user()->id;
    $comment->save();
    $time = date("l h:i a",strtotime($comment->created_at));
    $total_comments = Comment::where('memory_id',$data['memory_id'])->count();
    

    $event = Event::find($data['event_id']);
    
    if($data['task_id'] != 0){
        $task = Task::find($data['task_id']);
        $subject = Auth::user()->name." Added a New Comment to ".$task->name." in ".$event->name;
                $msg = Auth::user()->name." <p>has commented on your ".$task->name." task in ".$event->name." with the following:</p>
<p>".$comment->comment."</p>

To access the event, <a href='".route('event.event_details',['event_id' => $data['event_id']])."' >Click Here</a> ";
$title = "New Comment on a Task Assigned to You";
        // send email to the user assigned to this task
        if($task->user_id && $task->user_id != Auth::user()->id){
            $user = User::find($task->user_id);
            
                Helpers::sendEmail($subject,$msg,$user,$title);
        }
        // send email to all the participants in this thread
        $comments = Comment::where('task_id',$data['task_id'])->groupBy('user_id')->get();
        foreach($comments as $commentt){
            $user = User::find($commentt->user_id);
            if($user->id != Auth::user()->id){
                Helpers::sendEmail($subject,$msg,$user,$title);

            }

        }    
    }

    if(isset($data['memory_id'])){
$memory = File::find($data['memory_id']);
        $subject = Auth::user()->name." Has commented on a memory ".$memory->file;
                $msg = Auth::user()->name." <p>has commented on a memory ".$memory->file." </p>

To access the event, <a href='".route('event.event_details',['event_id' => '1'])."' >Click Here</a> ";
$title = "New Comment Added";
        // send email to the user assigned to this task
        if($memory->user_id && $memory->user_id != Auth::user()->id){
            $user = User::find($memory->user_id);
            
                Helpers::sendEmail($subject,$msg,$user,$title);
        }
        // send email to all the participants in this thread
        $comments = Comment::where('memory_id',$data['memory_id'])->groupBy('user_id')->get();
        foreach($comments as $commentt){
            $user = User::find($commentt->user_id);
            if($user->id != Auth::user()->id){
                Helpers::sendEmail($subject,$msg,$user,$title);

            }

        }       
    }


    

return response()->json(['page'=>'none' ,'name' => Auth::user()->name , 'time' => $time,'comment'=>$comment->comment,'total_comments'=>$total_comments]);

}

public function show_memory($id){
    $memory = File::find($id);
    $comments = Comment::where('memory_id',$memory->id)->orderBy('created_at','DESC')->get();
    $comments_count = Comment::where('memory_id',$memory->id)->count();
    $data['partialView'] = 'Event.show_memory';
    $data['memory'] = $memory;
    $data['comments'] = $comments;
    $data['comments_count'] = $comments_count;
    return view('Event.base', $data);

}
//functions


}

resources/views/Event/event_details.blade.php
<style>
.comment_div{
	margin-left:10px;
	margin-bottom:30px;
}
.comment_div h5{
	color:#0088cc !important; 
	border-bottom:1px solid #d8d8d8; 
	padding-bottom:8px; 
	font-weight:bold;
}
.comment_div h5 span{
	color:#999; 
	font-weight:normal;
}
.comment_div p{
	margin:10px 0 !important;
}
.add_memory{
	position:fixed;
	top:50px;
	right:0;
	z-index:10000000000000000000000000000;
	opacity:0.8;
}
.add_memory:hover{
	opacity:1;
}
</style>
<a class="btn btn-success add_memory popup" href="{{route('files.add')}}"> + Add memory </a>
<div class="portlet light bordered">

    <div class="portlet-body form">
        <div class="row">
				<div class="col-md-12 news-page blog-page">
					<div class="row">
					  <div class="col-md-6 blog-tag-data">
							<img src="/images/cover.jpg" class="img-responsive" alt="">
                            <div class="row">
                            &nbsp;
                            </div>
							<div class="row">
								<div class="col-md-6">
									<ul class="list-inline blog-tags">
										<li>
											<i class="fa fa-map-marker"></i>
											
											{{$event->location}} 
									  </li>
									</ul>
								</div>
								<div class="col-md-6 blog-tag-data-inner">
									<ul class="list-inline">
										<li>
											<i class="fa fa-calendar"></i>
											
											{{ Carbon\Carbon::parse($event->start_time)->format('l M d, Y') }} 
									  </li>
                                        
                                      <i class="fa fa-clock-o"></i>
											
											{{ Carbon\Carbon::parse($event->start_time)->format('h:i a') }} - 
                                            {{ Carbon\Carbon::parse($event->end_time)->format('h:i a') }} 
										</li>
										
								  </ul>
								</div>
							</div>
							<div class="news-item-page">
								<p>
									 {{$event->description}}
							  </p>
								
								
						</div>
							<hr>
							<!--end media--><!--end media-->
							<hr>
					  </div>
					  <div class="col-md-6">
							
						  <div class="space20">
					      </div>
						  <div class="space20">
						    </div>
							
							<div class="tabbable-line">
								<ul class="nav nav-tabs">
									<li class="active">
										<a data-toggle="tab" href="#tab_1_1">
									  Participants </a>
									</li>
									<li class="hide">
										<a data-toggle="tab" href="#tab_1_2">
									  Invited </a>
									</li>
								</ul>
								<div class="tab-content">
									<div id="tab_1_1" class="tab-pane active" style="height:580px; overflow:auto;">
										<table class="table table-striped table-bordered table-advance table-hover">
														
														<tbody>
                                                        @foreach($event->AcceptedUsers as $user)
														<tr>
															<td>
																<a href="javascript:;">
																<i class="fa fa-user" aria-hidden="true"></i> &nbsp;{{$user->name}} </a>
															</td>
															<td width="20" align="center" bgcolor="#669900" ><div class="tooltips"  data-placement="top" data-original-title="Attending" style="width:10px; height:20px;">&nbsp;</div></td>
						                  </tr>
                                                          @endforeach
                                                          @foreach($event->PendingUsers as $user)
														<tr>
														  <td>
																<a href="javascript:;">
																<i class="fa fa-user" aria-hidden="true"></i> &nbsp; {{$user->name}} </a>
															</td>
															<td width="20" align="center" bgcolor="#0088cc" >
                                                            <div class="tooltips"  data-placement="top" data-original-title="Pending" style="width:10px; height:20px;">&nbsp;</div>
                                                            
                                                            </td>
					                      </tr>
                                                          @endforeach
														
														</tbody>
													                                                                                                                      
														</table>
                                                 
									</div>
									<div id="tab_1_2" class="tab-pane">
                                    <table class="table table-striped table-bordered table-advance table-hover">
														
														<tbody>
                                                        @foreach($event->PendingUsers as $user)
														<tr>
															<td>
																<a href="javascript:;">
																{{$user->name}} </a>
															</td>
									  </tr>
                                                          @endforeach
														
														</tbody>
									  </table>
										
								  </div>
								</div>
							</div>
							<div class="space20">
							</div>
							<div class="space20">
						    </div>
					  </div>
					</div>
				</div>
			</div>
</div>

</div>
@if(count($files)!= 0)
<h3> Memories </h3>
<div id="gallery">

<div id="gallery-content">
<div id="gallery-content-center">
@foreach($files as $file)
        	@if($file->processed == 0)
            <a href="{{route('event.show_memory',['memory_id' => $file->id])}}" class="gallery-item" >
            	<img src="/uploads/{{$file->hash}}/{{$file->file}}" style="max-width:250px;" />
            </a>
            @endif
            @if($file->processed == 1)
            <a href="{{route('event.show_memory',['memory_id' => $file->id])}}" class="gallery-item" >
            	<img src="https://img.youtube.com/vi/{{$file->youtube_id}}/0.jpg" style="max-width:250px;" />
            </a>
            @endif
            @if($file->processed == 2)
            <a href="{{route('event.show_memory',['memory_id' => $file->id])}}" data-id="{{$file->id}}"  class="gallery-item refresh_video" title="Video is processing, refresh the page later"  >
            	<img src="/images/loadin.gif" style="max-width:150px;" />
            </a>
            @endif
        @endforeach




</div>
</div>
</div>
</div>
@endif

<div class="portlet light bordered">
<div class="portlet-title">
        <div class="caption font-color">
          <i class="fa fa-check font-color"></i> Pick up a dish to prepare
      </div>

    <div class="portlet-body form">
        <table class="table table-striped table-bordered table-hover table-dt" >

        
        <tbody>
        <?php $old_cat = "";?>
        @foreach($event->PoolDishes as $index => $task)
        <?php $new_cat = $task->category ;?>
        @if($new_cat != $old_cat)
        <tr class="odd gradeX">
          <td colspan="4" valign="middle" bgcolor="#0088CC"><span style="color:#fff; font-weight:bold;">{{$task->category}}</span></td>
          </tr>
          
        <tr class="tr-head">
            <th valign="middle">Dish</th>
            <th valign="middle">Description</th>
            <th valign="middle">Category</th>
            <th valign="middle">
                        Actions
                    </th>
</tr>
        
          @endif
        <tr class="odd gradeX" id="data-row-{{$task->id}}">
           <td valign="middle">{{$task->name}} <a href="{{route('task.comments',['task_id' => $task->id])}}" class="popup" ><i class="fa fa-edit font-color"></i> Comments {{$task->commentsCount->count()}}</a></td>
           <td valign="middle">{{$task->description}}</td>
           <td valign="middle">{{$task->category}}</td>
          <td valign="middle">
            
            <a href="{{route('task.pickup',['task_id'=>$task->id , 'user_id' => Auth::user()->id ])}}" data-method="get" class="btn btn-success confirm_action" ><i class="fa fa-check"></i> Pickup</a>
            
            
          </td>
</tr>
<?php $old_cat = $task->category ;?>
        @endforeach
    </table>
</div>

</div>
</div>

<div class="portlet light bordered">
<div class="portlet-title">
        <div class="caption font-color">
            <i class="fa fa-check font-color"></i> Picked up dishes
      </div>

    <div class="portlet-body form">
        <table class="table table-striped table-bordered table-hover table-dt" >

        <thead>
        <tr class="tr-head">
            <th valign="middle">Dish</th>
            <th valign="middle">Description</th>
            <th valign="middle">Category</th>
            <th valign="middle">Assigned to</th>
            <th valign="middle">Assigned By</th>
            <th valign="middle">Approved By</th>
          <th valign="middle">
                        Status
                    </th>
          </tr>
        </thead>
        <tbody>
        @foreach($event->AssignedDishes as $index => $task)
         
        <tr class="odd gradeX" id="data-row-{{$task->id}}">
           <td valign="middle">{{$task->name}} <a href="{{route('task.comments',['task_id' => $task->id])}}" class="popup" ><i class="fa fa-edit font-color"></i> Comments {{$task->commentsCount->count()}}</a></td>
           <td valign="middle">{{$task->description}}</td>
           <td valign="middle">{{$task->category}}</td>
           <td valign="middle">
           <?php if(isset($task->user->name)){?>
           {{$task->user->name}}
           <?php ;}?>
           </td>
           <td valign="middle">
           <?php if(isset($task->assigned_by->name)){?>
                        {{$task->assigned_by->name}}
                        <?php ;}?>
                    </td>
          <td valign="middle">
          @if($task->assigned_by_id == $task->user_id)
          Organizer
          @else
          <?php if(isset($task->user->name)){?>
          {{$task->user->name}}
          <?php ;}?>
          @endif
          </td>
          <td valign="middle">
          @if($task->confirmed == 1)
                        <button class="btn btn-success" style="background-color:#669900 !important; border-color:#669900 !important;" ><i class="fa fa-check-circle" aria-hidden="true"></i> Confirmed</button>
                        @else
                       <button class="btn btn-primary" ><i class="fa fa-exclamation-circle" aria-hidden="true"></i> Pending</button>
                       
                        @endif
                        @if(Auth::user()->id == $task->user_id)
                       <a href="{{route('event_user.reply_task',['id'=>$task->id , 'reply' => 0 ])}}" data-method="get" class="btn btn-delete confirm_action" ><i class="fa fa-remove"></i> Release</a>
                        @endif
                    </td>
          </tr>
        @endforeach
    </table>
</div>

</div>
</div>


<h3> Comments (<span id="comments_count">{{$comments_count}}</span>)</h3>
<form id="event_comments" class="ajax_form j-forms" method="post"
 action="{{route('comment.do_comment')}}">
 <div class="unit form-group ">
                    
                    <div class="input">
					<label class="icon-right">
                        <i class="fa fa-comment"></i>
                    </label>
                    <textarea  class="form-control comment"  name="comment"  data-name="Comment"  data-validation="" placeholder="Add a comment..." /></textarea>
                    </div>
</div>
<input name="event_id" value="{{$event->id}}" type="hidden" />
<input name="task_id" value="0" type="hidden" />
<input type="reset" name="Reset" id="reset_button" value="Reset" style="display:none;" />
</form>
<div id="comment_container">

@foreach($comments as $comment)
<div class="comment_div" >
<h5 ><?php if(isset($comment->user->name)){?>{{$comment->user->name}}<?php ;}?> <span class="pull-right" ><?php echo date("l h:i a",strtotime($comment->created_at));?></span></h5>
<p>{{$comment->comment}}</p>
</div>
@endforeach
<div class="comment_div" style="display:none;">
<h5 >@@name@@ <span class="pull-right" >@@time@@</span></h5>
<p>@@comment@@</p>
</div>

</div>
<div class="comment_div clone_comment" style="display:none;">
<h5 >--name-- <span class="pull-right" >--time--</span></h5>
<p>--comment--</p>
</div>





        

    

resources/views/Event/events.blade.php
<div class="portlet light">
    <div class="portlet-title">
        <div class="caption font-color">
            <i class="fa fa-globe font-color"></i> Event
        </div>

    </div>
    <div class="portlet-body">
        <div class="table-toolbar">
            <div class="row">
                <div class="col-md-6">
                    <div class="btn-group">
                        <a class="btn color pjax-link"  href="{{route('event.init')}}">
                            Add New <i class="fa fa-plus"></i>
                        </a>
                       
                    </div>
                </div>
{{--@reorder-button@--}}

            </div>
        </div>

    </div>
    <form id="search-form">
        {{csrf_field()}}
        
        <div class="form-group"></div>
    </form>

    <table class="table table-striped table-bordered table-hover table-dt" id="table-dt">

        <thead>
        <tr class="tr-head">
            <th valign="middle" class="no-sorting table-checkbox-col">
                <input type="checkbox" class="group-checkable">
            </th>
            <th valign="middle">
                        Event Name
                    </th>
<th valign="middle">
                        Location
                    </th>
<th valign="middle">
                        End Time
                    </th>
<th valign="middle">
                        Start Time
                    </th>
<th valign="middle">
                        Actions
                    </th>

        </tr>
        </thead>
        <tbody>
        @foreach($events as $index => $event)
        <tr class="odd gradeX" id="data-row-{{$event->id}}">
           <td valign="middle">
               <input type="hidden" value="{{$event->id}}" class="reorder-vals"/>
               <input type="checkbox" name="items[]" class="table-checkbox" value="{{$event->id}}"/>
           </td>
            <td valign="middle">
            <a href="{{route('event.event_details' , ['event_id' => $event->id])}}">
                        {{$event->name}}
                        </a>
                    </td>
<td valign="middle">
                        {{$event->location}}
                    </td>
<td valign="middle">
                        {{$event->end_time}}
                    </td>
<td valign="middle">
                        {{$event->start_time}}
                    </td>
<td valign="middle">
                        <a href="{{route('event.events_1Edit',['id'=>$event->id])}}" class="btn btn-edit  pjax-link" ><i class="fa fa-edit"></i> Edit</a>
                        <a href="{{route('event.delete',['id'=>$event->id ])}}" data-method="delete" class="btn btn-delete remove-stuff" ><i class="fa fa-remove"></i> Delete</a>
                    </td>
        </tr>
        @endforeach
        </tbody>
    </table>
</div>
</div>